name: CI/CD - Deploy Infraestructure

on:
  push:
    branches:
      - main
    paths:
      - "garage-management-infra/**"
  workflow_dispatch:

env:
  TF_VAR_lambda_auth_arn: ${{ secrets.LAMBDA_ARN }}


permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform Provisioning
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: garage-management-infra

    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 3. Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: 4. Terraform Init
        id: init
        run: terraform init

      - name: 5. Terraform Validate & Format
        run: |
          terraform fmt -check
          terraform validate

      - name: 6. Terraform Plan
        id: plan
        run: terraform plan -input=false

      - name: 7. Terraform Apply
        run: terraform apply -auto-approve -input=false
